apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cashflow-api
  name: cashflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cashflow-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cashflow-api
    spec:
      containers:
      - image: ghcr.io/shehanka/cashflow-api:latest
        name: cashflow-api
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cashflow-api
spec:
  type: NodePort
  selector:
    app: cashflow-api
  ports:
    - port: 80
      targetPort: 80
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: cashflow-api
#  annotations:
#    kubernetes.io/ingress.class: addon-http-application-routing
#spec:
#  rules:
#    # https://docs.microsoft.com/en-us/azure/aks/http-application-routing
#    - host: cashoflow-api.AKS_URL
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: cashflow-api
#                port:
#                  number: 80
